# Generated by Django 3.1.7 on 2021-03-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('dob', models.DateField(null=True)),
                ('position', models.CharField(choices=[('Point guard', 'Point guard'), ('Shooting guard', 'Shooting guard'), ('Small forward', 'Small forward'), ('Power forward', 'Power forward'), ('Center', 'Center')], max_length=20, null=True)),
                ('dominant_hand', models.CharField(choices=[('Right hand', 'Right hand'), ('Left hand', 'Left hand')], max_length=20, null=True)),
                ('nationality', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xCoor', models.FloatField()),
                ('yCoor', models.FloatField()),
                ('isGoal', models.BooleanField()),
                ('playerID', models.ManyToManyField(to='run.Players')),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='teamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='run.teams'),
        ),
    ]
