# Generated by Django 3.1.7 on 2021-05-28 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_averageteamstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='AveragePlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(110)])),
                ('field_goals', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('field_goal_attempts', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('field_goal_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('three_point_field_goal', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('three_point_field_goal_attempts', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('three_point_field_goal_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('two_point_field_goal', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('two_point_field_goal_attempts', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('two_point_field_goal_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('free_throws', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('free_throw_attempts', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('free_throw_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('offensive_rebounds', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('defensive_rebounds', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total_rebounds', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('assists', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('steals', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('turnovers', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('blocks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('personal_fouls', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('points', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='assists',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='blocks',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='defensive_rebounds',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='offensive_rebounds',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='personal_fouls',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='points',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='steals',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='total_rebounds',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='turnovers',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
